### ISSUE TITLE
KillFeed Error: TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by werewolfboy13** [Thomas-Smyth/SquadJS#230]
### Description of Issue

I am getting a lot of error logs with this printout for the discord kill feed plugin. Is this anything I need to worry about or can I set it to ignore?

### Errors or Screenshots of Issue

```
SquadServer][1] Updating layer information...
[SquadServer][1] Updated layer information.
[SquadServer][1] Updating player list...
[SquadServer][1] Updating player list...
[SquadServer][1] Updating player list...
[SquadServer][1] Updated player list.
[SquadServer][1] Updated player list.
TypeError: Cannot read properties of null (reading 'name')
    at DiscordKillFeed.onWound (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/discord-killfeed.js:71:28)
    at SquadServer.emit (node:events:532:35)
    at SquadLogParser.<anonymous> (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/index.js:241:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by werewolfboy13** [comment]
I am also noticing this in some of the error stacks generated with it.

```
[SCBLInfo][1] Failed to fetch Squad Community Ban List data for player undefined (Steam ID: undefined):  TypeError: Cannot read properties of null (reading 'steamID')
    at SCBLInfo.onPlayerConnected (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/scbl-info.js:88:27)
    at SquadServer.emit (node:events:532:35)
    at SquadLogParser.<anonymous> (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/index.js:203:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I noticed an influx of these when I enabled the plugin, the SCBL error is a known issue that shouldn't be causing an issue.

**Comment by Indy79** [comment]
@werewolfboy13 i think the issue come when the player is inside a vehicule

**Comment by Thomas-Smyth** [comment]
https://github.com/Team-Silver-Sphere/SquadJS/pull/240
