### ISSUE TITLE
Node Import Error

### ISSUE THREAD

**Issue by hink** [Thomas-Smyth/SquadJS#232]
### Description of Issue

**SyntaxError: Cannot use import statement outside a module**

### Errors or Screenshots of Issue

```
node@b591617e0a9a:/app$ node /config/index.js
(node:23) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/config/index.js:1
import SquadServerFactory from 'squad-server/factory';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
node@b591617e0a9a:/app$ node --version
v13.14.0
```

### Squad Information
 * SquadJS Version: 3.2.0
 * Squad Version: N/A

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System: Docker (Debian 10 image)
 * NodeJS Version: 13.14.0 (same behavior on 14.x)
 * Yarn Version: 1.22.5

**Comment by hink** [comment]
My mistake -- was trying to load an index.js outside of the app dir.
