### ISSUE TITLE
Unable to connect to discord.

### ISSUE THREAD

**Issue by byworkteam** [Thomas-Smyth/SquadJS#242]
### Description of Issue
Unable to connect to discord.
### Errors or Screenshots of Issue
[SquadServerFactory][1] Starting discord connector discord...
C:\Users\Administrator\Desktop\SQUADJS\SquadJS-3.3.0\node_modules\discord.js\src\rest\RequestHandler.js:93
        throw new HTTPError(error.message, error.constructor.name, error.status, request.method, request.path);
              ^

HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (C:\Users\Administrator\Desktop\SQUADJS\SquadJS-3.3.0\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\Administrator\Desktop\SQUADJS\SquadJS-3.3.0\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async WebSocketManager.connect (C:\Users\Administrator\Desktop\SQUADJS\SquadJS-3.3.0\node_modules\discord.js\src\client\websocket\WebSocketManager.js:138:9)
    at async Client.login (C:\Users\Administrator\Desktop\SQUADJS\SquadJS-3.3.0\node_modules\discord.js\src\client\Client.js:223:7)
    at async Function.createConnector (file:///C:/Users/Administrator/Desktop/SQUADJS/SquadJS-3.3.0/squad-server/factory.js:105:7)
    at async Function.buildFromConfig (file:///C:/Users/Administrator/Desktop/SQUADJS/SquadJS-3.3.0/squad-server/factory.js:67:37)
    at async main (file:///C:/Users/Administrator/Desktop/SQUADJS/SquadJS-3.3.0/index.js:14:7) {
  code: 500,
  method: 'get',
### Squad Information
 * SquadJS Version:3.3
 * Squad Version:

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System:
 * NodeJS Version:
 * Yarn Version:

**Comment by byworkteam** [comment]
This is a failure when I try to connect to discord, I fill in my token, but can't connect

**Comment by byworkteam** [comment]
I seem to have the wrong tag for this question, if you see it, please help me with the tag

**Comment by byworkteam** [comment]
I don't know which part this belongs to, so I filled in the core part, if you see it please help me correct the location of this question

**Comment by werewolfboy13** [comment]
Closing issue as it is 1+ month out. If the issue still persists please reach out in the discord.
