### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by anklav24** [Thomas-Smyth/SquadJS#276]
I have this error in logs.

```
(node:15853) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

Do I need to worry or to do something with it?

**Comment by ect0s** [comment]
You shouldn't need to worry about it; 

However, it would be useful to see what else is happening when this occurs; 

If this is a common occurrence for your set, please let run with `node --trace-warnings` and copy the entire error callstack so we can check if its a plugin or core squadjs thats causing the warning.

**Comment by anklav24** [comment]
This is not a core bug. I believe, I need to take a glance on my code. 
```
│Jan 25 08:46:42 squad-vsrv taskset[44197]: (node:44197) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increas┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at _addListener (events.js:475:17)                                                                                                                              ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at Socket.addListener (events.js:497:10)                                                                                                                        ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at Socket.Readable.on (internal/streams/readable.js:852:35)                                                                                                     ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at Socket.once (events.js:541:8)                                                                                                                                ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at file:///home/squad/SquadJS/main_server/core/rcon.js:318:19                                                                                                   │
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at new Promise (<anonymous>)                                                                                                                                    │
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at SquadRcon.write (file:///home/squad/SquadJS/main_server/core/rcon.js:259:12)                                                                                 ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at SquadRcon.execute (file:///home/squad/SquadJS/main_server/core/rcon.js:255:17)                                                                               ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at SquadRcon.warn (file:///home/squad/SquadJS/main_server/squad-server/rcon.js:201:16)                                                                          ┤
│Jan 25 08:46:42 squad-vsrv taskset[44197]:     at Timeout._onTimeout (file:///home/squad/SquadJS/main_server/squad-server/plugins/auto-kick-unassigned-custom.js:212:24)
```

**Comment by anklav24** [comment]
```
    // continuously warn player at rate set in options
    tracker.warnTimerID = setInterval(async () => {
      const msLeft = this.kickTimeout - this.warningInterval * (tracker.warnings + 1);

      // clear on last warning
      if (msLeft < this.warningInterval + 1) clearInterval(tracker.warnTimerID);

      const timeLeft = this.msFormat(msLeft);
      this.server.rcon.warn(tracker.player.steamID, `${this.options.warningMessage} - ${timeLeft}`);  // This is the string 212, I don't get it
      this.verbose(2, `Warning: ${tracker.player.name} (${timeLeft})`);
      tracker.warnings++;
    }, this.warningInterval);
```

**Comment by ect0s** [comment]
https://github.com/Team-Silver-Sphere/SquadJS/blob/62b89090648fdb9ccf32283d313e88bf62dc5f3b/core/rcon.js#L318

So, each RCON call does setup a listener for Errors, this may just be the number of pending RCON calls exceeding the default warning threshold, but not necessarily a bug. 

If, for example, your warning many players on top of other calls into RCON, the pending callbacks will exceed 10.

This is probably not something to worry about, as its well within the design, but perhaps while I'm tinkering around in the RCON client we can avoid setting up this listener.

**Comment by anklav24** [comment]
Thanks for the explanation.
